### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by Luis-Munu** [Backend2121/SimpleThingsProvider#1]
After a fresh install of the latest release and downloading the requested .NET version 6.0.0 the app won't open at all. No window pops up.

**Comment by cabiamdos** [comment]
Hello, I have exactly the same issue, here I attach a GIF that proof it.
I am using windows 10.

As you can see I have .net 6 installed because when I click on the setup button it says _modify setup_ and I have three options _repair uninstall_ or _close_
![Animation](https://user-images.githubusercontent.com/82284393/209436669-e314b924-79a1-4899-9b7e-ad08e2fffcf6.gif)

**Comment by Backend2121** [comment]
Might be worth a shot to see if "repair" changes something (maybe it is detecting the Core Runtime as the actual Desktop Runtime).
Otherwise rebooting your PC and see if the error is gone never hurts.

**Comment by cabiamdos** [comment]
I believe the issue is because I don't have the visual studio 2022, I have the 2019 version only and I think it requires the .net 6.0 core and framework installed too. But I don't have more space on this machine to install anything else right now so I will let you know if when I install that problem solved.
Thanks
