### ISSUE TITLE
Version 2.0 doesn't open

### ISSUE THREAD

**Issue by AlbertoAIG** [Backend2121/SimpleThingsProvider#5]
Hello,

Version 2.0 does not open after installing and configuring the extensions and modules in Windows 11 latest version.

What could be wrong?

Thank you

**Comment by Backend2121** [comment]
Could you check the Windows Event Viewer? There will be an error regarding STP.

**Comment by AlbertoAIG** [comment]
> Could you check the Windows Event Viewer? There will be an error regarding STP.

Nombre de la aplicación con errores: SimpleThingsProvider.exe, versión: 1.0.0.0, marca de tiempo: 0x6331eb0e
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.22621.2428, marca de tiempo: 0x9223bda8
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x0000000000064ffc
Identificador del proceso con errores: 0x0x2AAC
Hora de inicio de la aplicación con errores: 0x0x1DA076F279C5DC3
Ruta de acceso de la aplicación con errores: C:\Program Files (x86)\SimpleThingsProvider\SimpleThingsProvider.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\System32\KERNELBASE.dll
Identificador del informe: ca0c01cb-e09b-4e87-ae9e-eee4da7a77a4
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:




Name of the application with errors: SimpleThingsProvider.exe, version: 1.0.0.0, timestamp: 0x6331eb0e

Name of the module with errors: KERNELBASE.dll, version: 10.0.22621.2428, timestamp: 0x9223bda8

Exception code: 0xe0434352

Error displacement: 0x0000000000064ffc

Identifier of the process with errors: 0x0x2AAC

Application start time with errors: 0x0x1DA076F279C5DC3

Application path with errors: C:\Program Files (x86)\SimpleThingsProvider\SimpleThingsProvider.exe

Path of the module with errors: C:\WINDOWS\System32\KERNELBASE.dll

Report ID: ca0c01cb-e09b-4e87-ae9e-eee4da7a77a4

Full name of the package with errors:

Relative application identifier of the package with errors:

**Comment by Alkhymia** [comment]
Download "STP_Setup.msi", run it (smartscreen will probably block it), finish the installation by leaving everything as is and start downloading the Modules/Extensions you are interested in from the same page where you downloaded the Setup, extract the "STP" folder from the ".zip" file(s) inside your Documents folder and run STP!

As an example for the path:
C:\Users\{USER}\Documents\STP\Modules\SomethingModule.dll
C:\Users\{USER}\Documents\STP\Extensions\SomethingExtension.dll

You need the modules and extensions on your documents folder :S

**Comment by rbbrandon** [comment]
I have the same issue, and i'll add to the event viewer crash log:

`Application: SimpleThingsProvider.exe
CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'SimpleThingsProvider.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at SimpleThingsProvider.MainWindow..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at SimpleThingsProvider.App.Main()
`

**Comment by AlbertoAIG** [comment]
hi, 

same issue with 2.0.1:

[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <System>
  <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" /> 
  <EventID>1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-11-11T15:47:00.7595696Z" /> 
  <EventRecordID>2488</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="12996" ThreadID="13000" /> 
  <Channel>Application</Channel> 
  <Computer>Legion_Go</Computer> 
  <Security UserID="S-1-5-21-3740305151-759961614-1414316486-1001" /> 
  </System>
[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <EventData>
  <Data Name="Bucket">1571261199603059844</Data> 
  <Data Name="BucketType">4</Data> 
  <Data Name="EventName">APPCRASH</Data> 
  <Data Name="Response">No disponible</Data> 
  <Data Name="CabId">0</Data> 
  <Data Name="P1">SimpleThingsProvider.exe</Data> 
  <Data Name="P2">1.0.0.0</Data> 
  <Data Name="P3">64b073ea</Data> 
  <Data Name="P4">KERNELBASE.dll</Data> 
  <Data Name="P5">10.0.22621.2506</Data> 
  <Data Name="P6">5a736bb8</Data> 
  <Data Name="P7">e0434352</Data> 
  <Data Name="P8">000000000006565c</Data> 
  <Data Name="P9" /> 
  <Data Name="P10" /> 
  <Data Name="AttachedFiles">\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d0405fc6-232e-454c-a035-439f5694fcdb.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.05b26468-205a-43fb-b54a-2d826e195ca4.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b441b1db-a5aa-4964-ba17-db9275fbc12f.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.40f83a48-df4b-4979-a273-239286943283.tmp.txt \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eec8db97-e163-414e-9eed-1debfd2a7fa2.tmp.xml</Data> 
  <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_SimpleThingsProv_f1184efef0c01ae4d1f71b4b9c96ee93fee341_030f5d9b_1e93a4a2-0fcd-41b1-9ee9-efd0aae63660</Data> 
  <Data Name="AnalysisSymbol" /> 
  <Data Name="Rechecking">0</Data> 
  <Data Name="ReportId">a585c8bb-8e95-4cf7-8699-9dfeb8eeb817</Data> 
  <Data Name="ReportStatus">268435456</Data> 
  <Data Name="HashedBucket">44aec1b15b6c27cd15ce3dbc73b1cc84</Data> 
  <Data Name="CabGuid">0</Data> 
  </EventData>
  </Event>

[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-11-11T15:46:58.0069768Z" /> 
  <EventRecordID>2487</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="12996" ThreadID="13000" /> 
  <Channel>Application</Channel> 
  <Computer>Legion_Go</Computer> 
  <Security UserID="S-1-5-21-3740305151-759961614-1414316486-1001" /> 
  </System>
[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <EventData>
  <Data Name="AppName">SimpleThingsProvider.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">64b073ea</Data> 
  <Data Name="ModuleName">KERNELBASE.dll</Data> 
  <Data Name="ModuleVersion">10.0.22621.2506</Data> 
  <Data Name="ModuleTimeStamp">5a736bb8</Data> 
  <Data Name="ExceptionCode">e0434352</Data> 
  <Data Name="FaultingOffset">000000000006565c</Data> 
  <Data Name="ProcessId">0x3250</Data> 
  <Data Name="ProcessCreationTime">0x1da14b64d1febe8</Data> 
  <Data Name="AppPath">C:\Program Files (x86)\SimpleThingsProvider\SimpleThingsProvider.exe</Data> 
  <Data Name="ModulePath">C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data Name="IntegratorReportId">a585c8bb-8e95-4cf7-8699-9dfeb8eeb817</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>

[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-11-11T15:46:57.8804868Z" /> 
  <EventRecordID>2486</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="12880" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Legion_Go</Computer> 
  <Security /> 
  </System>
[-](https://github.com/Backend2121/SimpleThingsProvider/issues/5#) <EventData>
  <Data>Application: SimpleThingsProvider.exe CoreCLR Version: 6.0.2423.51814 .NET Version: 6.0.24 Description: The process was terminated due to an unhandled exception. Exception Info: System.Windows.Markup.XamlParseException: La invocación del constructor del tipo 'SimpleThingsProvider.MainWindow' que coincide con las restricciones de enlace especificadas produjo una excepción. ---> System.IO.FileLoadException: Could not load file or assembly 'C:\Users\alber\OneDrive\Documentos\STP\Modules\DownloaderExtension.dll'. El proveedor de archivos de nube no se está ejecutando. (0x8007016A) File name: 'C:\Users\alber\OneDrive\Documentos\STP\Modules\DownloaderExtension.dll' at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly) at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath) at System.Reflection.Assembly.LoadFrom(String assemblyFile) at SimpleThingsProvider.MainWindow.loadModules() at SimpleThingsProvider.MainWindow..ctor() at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions) --- End of inner exception stack trace --- at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri) at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream) at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc) at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties) at System.Windows.Application.DoStartup() at System.Windows.Application.<.ctor>b__1_0(Object unused) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state) at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.Run() at System.Windows.Application.RunDispatcher(Object ignore) at System.Windows.Application.RunInternal(Window window) at System.Windows.Application.Run() at SimpleThingsProvider.App.Main()</Data> 
  </EventData>
  </Event>

**Comment by Backend2121** [comment]
You have an Extension inside the Modules folder, Extensions MUST be inside the Extensions folder!

**Comment by AlbertoAIG** [comment]
All file inside module ends with "Module"
![Imagen 2](https://github.com/Backend2121/SimpleThingsProvider/assets/21199479/307167a7-f7df-45e9-ba7e-42c0fe86392f)
![Imagen](https://github.com/Backend2121/SimpleThingsProvider/assets/21199479/e835a7e1-0836-4afe-83b8-c4aac240d934)

**Comment by Backend2121** [comment]
This line in the error states the opposite: C:\Users\alber\OneDrive\Documentos\STP\Modules\DownloaderExtension.dll
Might be something caused by OneDrive i would guess

**Comment by AlbertoAIG** [comment]
I had STP folder duplicate on one drive and on local documento. I have deleted one drive stp folder and now it open. Thanks and sorry.
